import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        padding:10,
        flexDirection:'row',
        backgroundColor:'#252422'
    },
    image:{
        width:90,
        height:90,
        borderColor:'#EB5E28',
        borderWidth:0.5,
        borderRadius:50,
    },
    inner_container:{
        padding:10,
        flex:1,
        justifyContent:'center',
    },
    title:{
        fontWeight:'bold',
        fontSize:22,
        color:'#FFFCF2'
    },
    info_container:{
        flexDirection:'row',
        flex:1,
        alignItems:'center',
    },
    year:{
        fontSize:12,
        marginLeft:10,
        color:'#66635b',
        fontWeight:'bold',
    },
    artist:{
        color:'#FFFCF2'
    },
    soldout_title:{
        borderWidth:1,
        borderColor:'#eb5e28',
        padding:5,
        borderRadius:5,
        fontSize:12,
        color:'#FFFCF2'
    },
    soldout_container:{
        marginTop:5
    },
    content_container:{
        flexDirection:'row',
    },
});